---
- name: Configuration de Spark
  hosts: spark
  become: yes
  tasks:
    - name: Installation des dépendances Java
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Téléchargement de Spark
      get_url:
        url: "https://downloads.apache.org/spark/spark-3.0.1/spark-3.0.1-bin-hadoop2.7.tgz"
        dest: "/opt/spark-3.0.1-bin-hadoop2.7.tgz"

    - name: Extraction de Spark
      unarchive:
        src: "/opt/spark-3.0.1-bin-hadoop2.7.tgz"
        dest: "/opt/"
        remote_src: yes

    - name: Configuration des variables d'environnement pour Spark
      lineinfile:
        path: /etc/profile.d/spark.sh
        line: 'export SPARK_HOME=/opt/spark-3.0.1-bin-hadoop2.7'
        state: present
      notify:
        - Reload profile

    - name: Configuration du fichier spark-defaults.conf
      lineinfile:
        path: "{{ item.path }}"
        line: "{{ item.line }}"
      with_items:
        - { path: '/opt/spark-3.0.1-bin-hadoop2.7/conf/spark-defaults.conf', line: 'spark.mongodb.input.uri=mongodb://admin01:1234@mongodb:27017/database01' }
        - { path: '/opt/spark-3.0.1-bin-hadoop2.7/conf/spark-defaults.conf', line: 'spark.mongodb.output.uri=mongodb://admin01:1234@mongodb:27017/database01' }

  handlers:
    - name: Reload profile
      command: source /etc/profile.d/spark.sh
      become: yes
