---
- name: Configuration de MongoDB
  hosts: mongodb
  become: yes
  tasks:
    - name: Installation des dépendances
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mongodb
        - mongodb-server
        - python-pymongo

    - name: Démarrer MongoDB
      service:
        name: mongodb
        state: started
        enabled: yes

    - name: Configuration de l'utilisateur admin
      command: mongo admin --eval "db.createUser({user:'admin01', pwd:'1234', roles:[{role:'userAdminAnyDatabase', db:'admin'}]})"
      ignore_errors: yes

    - name: Configuration du fichier mongod.conf
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^#?bindIp:'
        line: 'bindIp: 0.0.0.0'
        state: present

    - name: Redémarrer MongoDB pour appliquer les changements
      service:
        name: mongodb
        state: restarted
