# install_mongodb.yml
- hosts: all
  become: yes
  tasks:
    - name: Import MongoDB public GPG key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present

    - name: Create MongoDB list file
      apt_repository:
        repo: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse'
        state: present

    - name: Update apt repo and cache
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Start MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes
